export const aboutCity = [
    {
        flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/POL_Pozna%C5%84_flag.svg/1920px-POL_Pozna%C5%84_flag.svg.png'
    },
    {
        title: 'City of Poznań',
        about: "Poznań is a city on the River Warta in west-central Poland, within the Greater Poland region. The city is an important cultural and business centre, and one of Poland's most populous regions with many regional customs such as Saint John's Fair (Jarmark Świętojański), traditional Saint Martin's croissants and a local dialect. Among its most important heritage sites are the Renaissance Old Town, Town Hall and Gothic Cathedral. Poznań is the fifth-largest and one of the oldest cities in Poland. As of 2021, the city's population is 529,410, while the Poznań metropolitan area (Metropolia Poznań) comprising Poznań County and several other communities is inhabited by over 1.1 million people. It is one of four historical capitals of medieval Poland and the ancient capital of the Greater Poland region, currently the administrative capital of the province called Greater Poland Voivodeship. Poznań is a center of trade, sports, education, technology and tourism. It is an important academic site, with about 130,000 students and Adam Mickiewicz University, the third largest Polish university. The city serves as the seat of the oldest Polish diocese, now being one of the most populous Catholic archdioceses in the country. The city also hosts the Poznań International Fair - the biggest industrial fair in Poland and one of the largest fairs in Europe. The city's other renowned landmarks include the National Museum, Grand Theatre, Fara Church and the Imperial Castle. Poznań is classified as global city by Globalization and World Cities Research Network. According to several rankings it is one of the most business-friendly cities in Poland It also ranks highly in safety and healthcare quality. The city of Poznań has also, many times, won the prize awarded by 'Superbrands' for a very high quality city brand. In 2012, the Poznań's Art and Business Center 'Stary Browar' won a competition organised by National Geographic Traveler and was given the first prize as one of the seven 'New Polish Wonders'. The official patron saints of Poznań are Saint Peter and Paul of Tarsus, the patrons of the cathedral. Martin of Tours - the patron of the main street Święty Marcin - is also regarded as one of the patron saints of the city."
    },
    {
        title: 'History',
        subtitle: 'End of World War I to World War II',
        subtitleContent: "At the end of World War I, the final Greater Poland Uprising in 1918 - 1919 brought Poznań and most of the region back to newly reborn Poland, which was confirmed by the Treaty of Versailles. The local German populace had to acquire Polish citizenship or leave the country. This led to a wide emigration of the ethnic Germans of the town's population - the town's German population decreased from 65,321 in 1910 to 5,980 in 1926 and further to 4,387 in 1934. In the interwar Second Polish Republic, the city again became the capital of Poznań Voivodeship. Poznań's university, today called Adam Mickiewicz University, was founded in 1919, and in 1924 the Poznań International Fair began. In 1929, the fair site was the venue for a major National Exhibition (Powszechna Wystawa Krajowa, popularly PeWuKa) marking the tenth anniversary of independence; it attracted around 4.5 million visitors. In the 1930s, the fair ranked as Europe's fourth largest organiser of international trade events. The city's boundaries were again expanded in 1925 to include Główna, Komandoria, Rataje, Starołęka, Dębiec, Szeląg and Winogrady, and in 1933 Golęcin and Podolany.",
        subtitle2: '1945 - Present',
        subtitle2Content: "Due to the expulsion and flight of German population Poznań's post-war population was almost uniformly Polish. The city again became a voivodeship capital. In 1950, the size of Poznań Voivodeship was reduced, and the city itself was given separate voivodeship status. This status was lost in the 1975 reforms, which also significantly reduced the size of Poznań Voivodeship. From left: Poznań protests of 1956 - the sign reads 'We demand bread!', Poznań Crosses - Monument to the Victims of June 1956 (1981) The Poznań 1956 protests are seen as an early instance of discontent with communist rule. In June 1956, a protest by workers at the city's Cegielski locomotive factory developed into a series of strikes and popular protests against the policies of the government. After a protest march on 28 June was fired on, crowds attacked the communist party and secret police headquarters, where they were repulsed by gunfire. Riots continued for two days until being quelled by the army; 67 people were killed according to official figures. A monument to the victims was erected in 1981 at Plac Mickiewicza."
    },

]